### PR TITLE
String gets std::wstring conversion

### PR DESCRIPTION
**Pull request by JeremyAgost**

### CODE REVIEW

**Comment by marc-groundctl** [comment]
This whole thing has byte ordering and sizing and UCS-2/UTF-16 problems, and I don't think there's a standard way to get this to work.  Since we only need this for Windows anyway, I'd recommend just putting these functions in an `#ifdef _WIN32` and calling `MultiByteToWideChar` with `CP_UTF8` (https://msdn.microsoft.com/en-us/library/dd319072.aspx).

**Comment by mitchellwong** [comment]
Researching stuff, don't merge yet. :gun:

**Comment by mitchellwong** [comment]
We don't need this. We can/should use boost::locale on boost::path so it converts from UTF-8. :gun:

**Comment by JeremyAgost** [comment]
There are some other changes in here I'd like to merge anyway.

**Comment by mitchellwong** [comment]
Then take out the unnecessary ones.

**Pull request merged**
